name: Build spore_devnet

on:
  push:
    branches:
      - main
    workflow_dispatch: {}
    schedule:
      - cron: '30 22 * * *' # Triggered every morning at 06:30 am (UTC time)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.14'

      - name: Run prepare.sh
        run: sh prepare.sh

      - name: Install Cross in spore-contract directory
        run: |
          cd spore-contract
          cargo install cross --git https://github.com/cross-rs/cross
          cd ..

      - name: Install Capsule in spore-contract directory
        run: |
          cd spore-contract
          cargo install ckb-capsule --git https://github.com/nervosnetwork/capsule.git --tag v0.10.1
          cd ..

      - name: Build contracts
        run: |
          cd spore-contract
          capsule build --release
          cd ..

      - name: Install Dependencies
        run: npm install

      - name: Build Lumos
        run: npm run build:lumos

      - name: Start Test
        run: npm run test:start > /dev/null 2>&1 &

      - name: Wait for 5 seconds
        run: sleep 5

      - name: Deploy Test
        run: npm run test:deploy

      - name: Clean Environment
        run: |
          rm -rf tmp
          rm lumos.json
